controller_list:
  - name: fake_arm_group_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_gripper_group_controller
    joints:
      - left_gripper_finger_joint
      - right_gripper_finger_joint